package graphQlDemo

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"graphQlDemo/ent"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context) ([]*ent.Review, error) {
	return r.client.Review.Query().All(ctx)
}

// Tools is the resolver for the tools field.
func (r *queryResolver) Tools(ctx context.Context) ([]*ent.Tool, error) {
	return r.client.Tool.Query().All(ctx)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	return r.client.User.Query().All(ctx)
}

// ID is the resolver for the id field.
func (r *reviewResolver) ID(ctx context.Context, obj *ent.Review) (int, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *toolResolver) ID(ctx context.Context, obj *ent.Tool) (int, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *ent.User) (int, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ReviewerID is the resolver for the reviewerID field.
func (r *createReviewInputResolver) ReviewerID(ctx context.Context, obj *ent.CreateReviewInput, data *int) error {
	panic(fmt.Errorf("not implemented: ReviewerID - reviewerID"))
}

// ReviwedtoolID is the resolver for the reviwedtoolID field.
func (r *createReviewInputResolver) ReviwedtoolID(ctx context.Context, obj *ent.CreateReviewInput, data *int) error {
	panic(fmt.Errorf("not implemented: ReviwedtoolID - reviwedtoolID"))
}

// ReviewIDs is the resolver for the reviewIDs field.
func (r *createToolInputResolver) ReviewIDs(ctx context.Context, obj *ent.CreateToolInput, data []int) error {
	panic(fmt.Errorf("not implemented: ReviewIDs - reviewIDs"))
}

// ReviewIDs is the resolver for the reviewIDs field.
func (r *createUserInputResolver) ReviewIDs(ctx context.Context, obj *ent.CreateUserInput, data []int) error {
	panic(fmt.Errorf("not implemented: ReviewIDs - reviewIDs"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Review returns ReviewResolver implementation.
func (r *Resolver) Review() ReviewResolver { return &reviewResolver{r} }

// Tool returns ToolResolver implementation.
func (r *Resolver) Tool() ToolResolver { return &toolResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// CreateReviewInput returns CreateReviewInputResolver implementation.
func (r *Resolver) CreateReviewInput() CreateReviewInputResolver {
	return &createReviewInputResolver{r}
}

// CreateToolInput returns CreateToolInputResolver implementation.
func (r *Resolver) CreateToolInput() CreateToolInputResolver { return &createToolInputResolver{r} }

// CreateUserInput returns CreateUserInputResolver implementation.
func (r *Resolver) CreateUserInput() CreateUserInputResolver { return &createUserInputResolver{r} }

type queryResolver struct{ *Resolver }
type reviewResolver struct{ *Resolver }
type toolResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type createReviewInputResolver struct{ *Resolver }
type createToolInputResolver struct{ *Resolver }
type createUserInputResolver struct{ *Resolver }
