// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphQlDemo

type UpdateProfileInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
}
