// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateReviewInput represents a mutation input for creating reviews.
type CreateReviewInput struct {
	Rating    int
	Comment   string
	CreatedAt *time.Time
}

// Mutate applies the CreateReviewInput on the ReviewMutation builder.
func (i *CreateReviewInput) Mutate(m *ReviewMutation) {
	m.SetRating(i.Rating)
	m.SetComment(i.Comment)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateReviewInput on the ReviewCreate builder.
func (c *ReviewCreate) SetInput(i CreateReviewInput) *ReviewCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreateToolInput represents a mutation input for creating tools.
type CreateToolInput struct {
	Name        string
	Description string
	Category    string
	Website     string
	ImageURL    string
	CreatedAt   *time.Time
}

// Mutate applies the CreateToolInput on the ToolMutation builder.
func (i *CreateToolInput) Mutate(m *ToolMutation) {
	m.SetName(i.Name)
	m.SetDescription(i.Description)
	m.SetCategory(i.Category)
	m.SetWebsite(i.Website)
	m.SetImageURL(i.ImageURL)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateToolInput on the ToolCreate builder.
func (c *ToolCreate) SetInput(i CreateToolInput) *ToolCreate {
	i.Mutate(c.Mutation())
	return c
}

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	Name         string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    *time.Time
}

// Mutate applies the CreateUserInput on the UserMutation builder.
func (i *CreateUserInput) Mutate(m *UserMutation) {
	m.SetName(i.Name)
	m.SetUsername(i.Username)
	m.SetEmail(i.Email)
	m.SetPasswordHash(i.PasswordHash)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateUserInput on the UserCreate builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c.Mutation())
	return c
}
